pipeline{
   agent{
        label 'ubuntu'
   }
   tools{
    maven 'M2_HOME'
   }
   stages{
    stage("analysis"){
        steps{
            withSonarQubeEnv('sonarqube'){
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Eng-Mike_geo-app'
            }
            
        }
    }
    stage("maven2"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:APBNx22dqnSjGPWrCcUZkLwhzkp \
            -T target/bio*.jar \
            "http://ec2-34-229-67-218.compute-1.amazonaws.com:8081/artifactory/geolocation/bio_${BUILD_ID}"'
        }
    }
    stage('docker logins'){
        steps{
            sh 'aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin \
            909977750497.dkr.ecr.us-east-1.amazonaws.com'
        }
    }
    stage('docker image build'){
        steps{
            sh 'docker build -t utc-app-dev:v.${BUILD_ID} .'
            sh 'docker build -t utc-app-dev:latest .'
        }
    }
    stage('Image tagging'){
        steps{
            sh 'docker tag utc-app-dev:v.${BUILD_ID} \
            909977750497.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
            sh 'docker tag utc-app-dev:latest \
            909977750497.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
        }
    }
    stage('push image'){
        steps{
            sh 'docker push 909977750497.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
            sh 'docker push 909977750497.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
        }
    }
   }
}
